# Exported from Render on 2024-08-28T11:36:02Z
services:
- type: web
  name: ReceipesUz
  runtime: python
  repo: https://github.com/AbdugafforovSH/Receipe
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn receipeuz.wsgi:application --bind 0.0.0.0:8080
version: "1"
